### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by kukwaa** [SLMNBJ/selectize-plugin-a11y#3]
Hi, I don't currently see any license associated with this project, and I'd really like to use it. There's some info about this here: https://help.github.com/articles/licensing-a-repository/

Could a license file be added to the repo?

Big thank you for making this plugin, by the way!

**Comment by SLMNBJ** [comment]
Hi @kukwaa, we are building a new version adding new features( new events, labels...) and we will incluse also a license. The plugin is free and you can use it in your project.
